// Generated by CoffeeScript 1.8.0
(function() {
  var handler, through2;

  through2 = require('through2');

  handler = function(data) {
    var escape, fileJSON, index, key, keys, val, _i, _len;
    keys = Object.keys(data).sort();
    fileJSON = "{\n";
    for (index = _i = 0, _len = keys.length; _i < _len; index = ++_i) {
      key = keys[index];
      escape = data[key].replace(/"/g, "\\\"");
      val = "  \"" + key + "\": \"" + escape + "\"";
      if (index !== keys.length - 1) {
        val += ",";
      }
      fileJSON += "" + val + "\n";
    }
    fileJSON += "}";
    return fileJSON;
  };

  module.exports = function() {
    return through2.obj(function(file, enc, cb) {
      var ctx, e;
      if (file.isNull()) {
        return cb(null, file);
      }
      try {
        ctx = file.contents.toString('utf8');
        file.contents = new Buffer(handler(JSON.parse(ctx)));
        return cb(null, file);
      } catch (_error) {
        e = _error;
        return cb(e, file);
      }
    });
  };

}).call(this);
